name: nextschool
description: A new Flutter project.

publish_to: "none"

version: 2.1.9+2057

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  advance_pdf_viewer: ^2.0.1
  after_layout: ^1.2.0
  age_calculator: ^1.0.0
  animated_button: ^0.2.0
  animations: ^2.0.3
  cached_network_image: ^3.2.1
  change_app_package_name: ^1.1.0
  cloud_firestore: ^3.1.17
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.5
  date_time_picker: ^2.1.0
  dio: ^4.0.6
  dotted_border: ^2.0.0+1
  dropdown_search: ^5.0.2
  equatable: ^2.0.3
  ext_video_player: ^0.1.2
  extended_image: ^6.2.1
  ffi: ^1.2.1
  file_picker: ^4.6.1
  file_saver: ^0.1.1
  file_utils: ^1.0.1
  firebase_core_platform_interface: 4.5.1
  firebase_crashlytics: ^2.8.1
  firebase_messaging: ^11.4.1
  flutter:
    sdk: flutter
  flutter_animated_button: ^2.0.2
  flutter_bloc: ^8.0.1
  flutter_cache_manager: ^3.3.0
  flutter_calendar_carousel: ^2.2.0
  flutter_chat_bubble: ^2.0.0
  flutter_cupertino_date_picker_fork: ^1.0.6
  flutter_cupertino_localizations: ^1.0.1
  flutter_dropdown_alert: ^1.0.4
  flutter_html: ^3.0.0-alpha.6
  flutter_inappwebview: ^5.4.4+3
  flutter_local_notifications: ^12.0.3
  flutter_localizations:
    sdk: flutter
  flutter_otp_text_field: ^1.1.1
  flutter_overlay_loader: ^2.0.0
  flutter_screenutil: ^5.5.4
  flutter_share: ^2.0.0
  flutter_svg: ^1.1.6
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  get: ^4.6.5
  google_fonts: ^3.0.1
  hexcolor: ^3.0.1
  horizontal_data_table: ^4.1.2+2
  html: ^0.15.0
  html_editor_enhanced: ^2.5.0
  http: ^0.13.4
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  lottie: ^1.3.0
  math_expressions: ^2.3.1
  modal_bottom_sheet: ^3.0.0-pre
  multiple_search_selection: ^2.2.1
  objectbox: ^1.6.2
  objectbox_flutter_libs: any
  open_file_safe: ^3.2.3
  package_info_plus: ^1.4.2
  path_provider: ^2.0.11
  pdf_viewer_plugin: ^2.0.1
  percent_indicator: ^4.2.2
  permission_handler: ^10.0.0
  pie_chart: ^5.3.2
  pinput: ^2.2.11
  provider: ^6.0.3
  recase: ^4.0.0
  rounded_loading_button: ^2.1.0
  rxdart: ^0.27.4
  scoped_model: ^2.0.0-nullsafety.0
  screenshot: ^1.2.3
  searchfield: ^0.7.2
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  signature: ^5.3.0
  sizer: ^2.0.15
  sms_receiver: ^0.4.1
  sn_progress_dialog: ^1.0.9
  syncfusion_flutter_pdfviewer: ^20.2.39-beta
  table_calendar: ^3.0.8
  timeago: ^3.2.2
  upgrader: ^4.2.1
  url_launcher: ^6.1.3
  video_viewer: ^1.2.7
  webview_flutter: ^3.0.4
  wiredash: ^1.5.0
  youtube_player_flutter: ^8.1.1

dev_dependencies:
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - assets/images/
    - assets/images/our_school/
    - assets/icons/
    - assets/svg/principal/
    - assets/svg/parent_onboarding/
    - assets/svg/teacher/
    - assets/svg/student/
    - assets/lottie/
    - assets/svg/
    - assets/

# fonts:
#   - family: popins
#     fonts:
#       - asset: fonts/poppins_medium.ttf
#         weight: 100
#       - asset: fonts/poppins_bold.ttf
#         weight: 200
#       - asset: fonts/poppins_light.ttf
#         weight: 300
#       - asset: fonts/poppins_regular.ttf
#         weight: 400
#       - asset: fonts/poppins_semibold.ttf
#         weight: 500
